### ISSUE TITLE
Add test to ensure groups and functional areas are only able to be viewd by vouched users 

### ISSUE THREAD

**Issue by justinpotts** [mozilla/mozillians-tests#187]
Write a test that checks to make sure groups and functional areas cannot be viewed with an unvouched account, and verify they can still be viewed by a vouched account.

https://bugzilla.mozilla.org/show_bug.cgi?id=1089894

**Comment by dabiid** [comment]
I started working on these changes

**Comment by dabiid** [comment]
@justinpotts I think this can be closed as complete. Let me know if more thorough tests are required and I'd be happy to take a look.

**Comment by davehunt** [comment]
Closing based on latest comment.
