### ISSUE TITLE
Update profile_edit tests

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/mozillians-tests#200]
... to reflect recent UI changes as described in https://bugzilla.mozilla.org/show_bug.cgi?id=1129848

Also tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1192832

**Comment by bebef1987** [comment]
@ppapadeas  what do you need on this view?
Can you identify some specific tests/workflows that you want automated and I can create some tests for them.

**Comment by ioana-chiorean** [comment]
cc @bebef1987 @viorelaioia @AndreiH @AlexLakatos @AlinT

**Comment by ppapadeas** [comment]
Edit of all fields to start with (and then save). Also first time creation of the profile.
On edits, privacy toggle changes should be included.

**Comment by johngian** [comment]
Bump with some details on that (since changes are already on [mozillians-dev](mozillians-dev.allizom.org)):

* We need to test new registration page
* We need to test new permission buttons
* We need to make sure per sub-form submission works as expected
* We need to make sure errors are only rendered for the sub-form that we submit

**Comment by ioana-chiorean** [comment]
@bebef1987, @alexlakatos - the guys - Pierros and Nemo - will be at MozFest too - can we try to finish this then?

**Comment by bebef1987** [comment]
Started to work on this.

Let's first fix the existing tests and then work on adding new tests for the new features

**Comment by ioana-chiorean** [comment]
<img src="https://cloud.githubusercontent.com/assets/1391451/11121879/ff835f56-8960-11e5-9cc0-e4f229a4e3a1.jpg" width="500" height="300" />
![photo_2015-11-12_17-11-54](https://cloud.githubusercontent.com/assets/1391451/11121880/ffa52316-8960-11e5-901e-b48305d0bb8f.jpg)

**Comment by bebef1987** [comment]
![u16sm](https://cloud.githubusercontent.com/assets/703611/11122605/9f167ce4-8964-11e5-952c-8b3ad06dd2fb.jpg)

**Comment by johngian** [comment]
@ioana-chiorean i see @akatsoulas smiling. That's a good sign :)

**Comment by ioana-chiorean** [comment]
No pressure @bebef1987  #justsaying
![photo_2015-11-12_17-49-59](https://cloud.githubusercontent.com/assets/1391451/11122899/dbe0cc64-8965-11e5-8d7a-7a3d10a760a2.jpg)

**Comment by AndreiH** [comment]
A PR is already opened for this. See https://github.com/mozilla/mozillians-tests/pull/204

**Comment by comzeradd** [comment]
This is fixed at #205. I think we can close this one.
