### ISSUE TITLE
Migrate from browserid to bidpom

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozillians-tests#218]
Due to conflicts with another package, the [browserid](https://pypi.python.org/pypi/browserid) package was renamed to [bidpom](https://pypi.python.org/pypi/bidpom/). This suite should be updated to use the new package. This involves changing the dependency name in `requirements.txt` and updating the use of the package to the new package structure. Documentation with examples for bidpom can be found [here](https://github.com/mozilla/bidpom/wiki/Examples-of-integrating-BIDPOM).

This issue is a suitable [Outreachy application contribution](https://github.com/davehunt/pytest-html#outreachy).

**Comment by anna-liao** [comment]
I would like to take this task for Outreachy application.  Thanks!

**Comment by davehunt** [comment]
Thanks @anna-liao, I'll assign it to you.

**Comment by anna-liao** [comment]
I'm very new to this.  Even though I'm familiar with python, I'm not familiar with Selenium.  What do I do beyond changing the dependency in requirements.txt?  Perhaps I'm in over my head.

**Comment by rbillings** [comment]
@anna-liao the primary change is to update the dependency. You'll also want to rename anything that refers to "browserid". Make sure the login tests continue to run. @davehunt might have more to add, but the intent was for this to be a good entry point into working with Selenium & not too tricky.

**Comment by anna-liao** [comment]
@rbillings Thanks for the suggestions!  I will fork and give it a try.

**Comment by davehunt** [comment]
@anna-liao the block of code [here](https://github.com/mozilla/mozillians-tests/blob/54b02fbac3d8e2376cb0c0de2897bcdd7dab740d/pages/base.py#L52-L57) needs to be updated based on [this example](https://github.com/mozilla/bidpom/wiki/Examples-of-integrating-BIDPOM#sign-in-with-username-and-password-via-the-helper-method). To verify, you'll need to run at least one test that uses this `login` method.

**Comment by anna-liao** [comment]
@davehunt Do I need a login on https://mozillians.allizom.org/ to test?

**Comment by davehunt** [comment]
@anna-liao yes - you'll need to sign up and create an account, and then store the credentials in a JSON file as covered [in the README](https://github.com/mozilla/mozillians-tests#credentials). You probably don't need to worry about having a vouched user, as just one test using the modified code should be enough to check there are no regressions. If you want to be thorough, create two accounts and we can get one vouched.

**Comment by davehunt** [comment]
@anna-liao are you still interested in working on this issue?

**Comment by anna-liao** [comment]
@davehunt Yes, I will give this a try, sorry about the delay!

**Comment by anna-liao** [comment]
So I made my edits and ran the tests a few times, including importing a few missing modules.  This is the output of my tests.  It's not clear to me whether it needs to pass all the test, or some of the tests?  It seems like many of the errors aren't due to the renaming.  Any help?
https://gist.github.com/anna-liao/525632613b3246d1a2918d5badb556c8

**Comment by davehunt** [comment]
@anna-liao it looks like you're running tests for some of your installed site-packages. I'm not sure why pytest is discovering these, but you might be able to avoid it by specifying the tests path on the command line. To help with diagnosing the test failures, could you perhaps run with `--html results.html` to generate a HTML report with screenshot and share that?

Also, your gist contains your credentials, so I would advise you change your password and delete your gist. You can avoid your tracebacks containing these data by running with `--tb short`.

**Comment by anna-liao** [comment]
@davehunt Thanks, I switched to using a fake gmail account, but the automated tests don't work because it redirects each test to a gmail login.  How to automate the gmail login part?

**Comment by davehunt** [comment]
Ah, you probably want to avoid Gmail because of that redirect. You could use restmail.net or some other provider of disposable email addresses.

**Comment by stephendonner** [comment]
Hi @anna-liao - are you still interested in and actively working on this?

**Comment by anna-liao** [comment]
@stephendonner Ah, sorry about this!  Maybe assign it to someone else, since I can't work on it now.  I apologize.

**Comment by stephendonner** [comment]
No worries, @anna-liao - I'll put it back into community availability; thanks!

**Comment by davehunt** [comment]
Persona is going to be shut down soon, and when it does BIDPOM will be redundant. Let's close this issue.
