### ISSUE TITLE
Create a user for accepting Group invitations

### ISSUE THREAD

**Issue by comzeradd** [mozilla/mozillians-tests#231]
We need a persistent account on all three instances to be used on the Group tests for invitations, to avoid spamming an existing email.

Once we have this we should update the code with the proper full name of this account.
https://github.com/mozilla/mozillians-tests/blob/master/tests/test_group.py#L88

**Comment by stephendonner** [comment]
Is there anything left to do here, @comzeradd ?

**Comment by comzeradd** [comment]
This was fixed at b32966b680727eb7dc3fb8348d138a22eeba3ebc
