### ISSUE TITLE
Do not use time-based names on group creation

### ISSUE THREAD

**Issue by johngian** [mozilla/mozillians-tests#253]
We occasionally get tracebacks from automated tests on mozillians-stage because of conflicting group names when creating new groups. I guess that it's triggered because we are running tests in parallel and the group name is time based [1]. We should consider replacing that to something more random like `uuid4` [2].

[1] https://github.com/mozilla/mozillians-tests/blob/master/tests/test_group.py#L21
[2] https://docs.python.org/2/library/uuid.html

**Comment by anu0012** [comment]
Hey, I want to take this.

**Comment by sachs7** [comment]
Hi, I created a PR for this issue (https://github.com/mozilla/mozillians-tests/pull/289). This is my first contribution to open source project. Let me know if it worked?

**Comment by stephendonner** [comment]
Closing this out due to https://github.com/mozilla/mozillians-tests/pull/291 being merged, which took care of this, I believe.
