### ISSUE TITLE
Stop relying on browser search when creating new groups

### ISSUE THREAD

**Issue by johngian** [mozilla/mozillians-tests#254]
For group testing related functionalities we are creating test group data. In order to do that we are instructing selenium to:
- Go to `settings` page
- Go to `groups` tab
- Search for string `find the group`
- Click the link
- Go to groups page
- Create group

The relevant code is here:
- https://github.com/mozilla/mozillians-tests/blob/7e67863b8e5b3c2145df9ad06c2750102ff1c48a/pages/settings.py#L213
- https://github.com/mozilla/mozillians-tests/blob/7e67863b8e5b3c2145df9ad06c2750102ff1c48a/pages/edit_profile.py#L39
- https://github.com/mozilla/mozillians-tests/blob/7e67863b8e5b3c2145df9ad06c2750102ff1c48a/pages/edit_profile.py#L50
- https://github.com/mozilla/mozillians-tests/blob/7e67863b8e5b3c2145df9ad06c2750102ff1c48a/pages/settings.py#L216

This triggers various side effects (because selenium is actually using browser search to find the string) and various test screenshots show failing tests because we are writing strings to the search bar instead of the required field.

Instead we should:
- Add a test that ensures this link exists
- Instead of going through this whole process when testing groups we should go directly to groups page by clicking `menu > groups`.

**Comment by stephendonner** [comment]
@bebef1987 want to take this?

**Comment by davehunt** [comment]
> selenium is actually using browser search to find the string

I have seen this too, and believe that the way Selenium is typing characters is triggering some behaviour in Mozillians to focus the search bar. As far as I can tell this is not triggered when using the remote server. I'm curious to see if it is also not triggered when using later Firefox versions with Marionette/GeckoDriver.

All that said, I agree that we should look to reducing the number of steps tests must travel through the UI. It's important to test just one thing wherever possible.

**Comment by johngian** [comment]
@davehunt I've seen this happening using saucelabs driver. Indeed using selenium grid these tests used to work fine.

+1 for the latter
