### ISSUE TITLE
Rip and replace BIDPOM from authentication-required tests

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mozillians-tests#262]
Given that Persona is officially dead November 30th, and Mozillians.org had a prod push earlier today, to remove/replace it, we should:

* remove BIDPOM from this mozillians-tests repo
* evaluate which currently-failing tests which require authentication we want to keep/restore
* either replace BIDPOM with another, yet-to-be-determined library, and/or:
* use pytest markers to skip the known, currently-failing tests

**Comment by stephendonner** [comment]
@viorelaioia is this something you've partially addressed, already?

**Comment by davehunt** [comment]
Yep, this was fixed by @viorelaioia in https://github.com/mozilla/mozillians-tests/commit/0808a67f520b331176fd26b971951253c7ef9332

**Comment by stephendonner** [comment]
@davehunt @viorelaioia great; shouldn't we also remove https://github.com/mozilla/mozillians-tests/blob/5ea84a9d85a9b05aa157833d34dcb9359702e36a/requirements/tests.txt#L2 then?

**Comment by davehunt** [comment]
@stephendonner Yep, we should. Thanks for spotting that.
