### ISSUE TITLE
Enable pyup.io for taking care of dependencies

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozillians-tests#265]
We want to enable [pyup.io](https://pyup.io/) for our projects to take care of automating the updates to our dependencies. Here's what's needed:

- [x] Move dependencies out of `tox.ini` and into requirements files. See https://github.com/mozilla/PyPOM/commit/ad21988d0364843808c07f3aaa656c6c16b971b2 for an example of this.
- [x] Add repository to pyup.io (@davehunt can take care of this once the above is merged).
- [x] Add pyup.io badges for updates and python 3 readyness. See https://github.com/mozilla/PyPOM/commit/931c41b964f1c9950983c078d0583ef708ac8af9 for an example of this.
- [x] Remove requires.io badge from README.
- [x] Remove repository from [requires.io](https://requires.io/) (@davehunt can take care of this once pyup.io is working)

**Comment by stephendonner** [comment]
Took a stab at this in https://github.com/mozilla/mozillians-tests/pull/268

**Comment by davehunt** [comment]
All done, thanks @stephendonner

**Comment by stephendonner** [comment]
❤️
