### ISSUE TITLE
test_that_search_returns_results_for_first_name fails at times due to case-sensitive assertion

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mozillians-tests#401]
@viorelaioia @akatsoulas @johngian /cc @davehunt 

Are searches meant to be case-insensitive (at least for names?)

https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/mozillians.adhoc/77/

1 tests failed.
FAILED:  tests.test_search.TestSearch.test_that_search_returns_results_for_first_name

Error Message:
AssertionError: assert 'Matt' in 'matt morgenroth'

Stack Trace:
tests/test_search.py:33: in test_that_search_returns_results_for_first_name
    assert query in profile_name
E   AssertionError: assert 'Matt' in 'matt morgenroth'

**Comment by stephendonner** [comment]
Re:ping?  Meant to ask you this in person, @akatsoulas @johngian @viorelaioia; it's still failing, albeit very sporadically, but it'd be great to adjust the test, or fix the app.

https://qa-master.fxtest.jenkins.stage.mozaws.net/job/mozillians.stage/87/console

Thanks!

**Comment by viorelaioia** [comment]
@stephendonner , thanks for opening the issue and sorry for late reply (I somehow missed this issue). 
Search is case-insensitive in mozillians. This looks like a problem with the test, and not the app. 
I will add a PR to fix it.

**Comment by stephendonner** [comment]
Thanks, @viorelaioia!

**Comment by viorelaioia** [comment]
Closing this, as the PR with the fix is merged.
