### ISSUE TITLE
DeprecationWarning: use driver instead

### ISSUE THREAD

**Issue by stephendonner** [mozilla/mozillians-tests#504]
We've got a deprecation warnings in our runs, here[0]:

```
17:19:30 pages/base.py:140
17:19:30   /home/jenkins/workspace/mozillians_PR-502-4L224KAUUARSAJ3P547AFTOHFD6TPE67ECDO5V5ACAJB3L56HBQA@2/pages/base.py:140: DeprecationWarning: use driver instead
17:19:30     return Settings(self.selenium, self.base_url)
```

[0] https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/mozillians/view/change-requests/job/PR-502/3/console

**Comment by davehunt** [comment]
@terrameijar basically replace instances of `self.selenium` with `self.driver`. You can test by running the tests with the `PYTEST_ADDOPTS` environment variable set to treat the deprecation warning as an error. For example, the Docker invocation from the README would change to:

```
docker run -it -e PYTEST_ADDOPTS="-W error::DeprecationWarning" --mount type=bind,source=/Users/dhunt/workspace/mozillians.json,destination=/variables.json,readonly mozillians-tests
```

**Comment by Aks1610** [comment]
is this done already???
If not i want to take this up.
